<?php
$text = "CGAGCACTCGTTATGAATTACTCGTTACTCGTTTAGTACACTCGTTTACTCGTTCATCTTGAGTACTCGTTGTATCTCTGGGACTCGTTCACTCGTTGTACTCGTTCACTATACTCGTTTACTCGTTACTCGTTGGCACACTCGTTCCACTCGTTCGACTCGTTACTCGTTACTCGTTACTCGTTAACTCGTTGTCACACTCGTTACTCGTTGATTCAACTCGTTACTCGTTACACTCGTTGGACTCGTTACTCGTTTCTTTCTAAACTCGTTCAAACTCGTTGTGCCACTCGTTTTTCACCATACTCGTTTCGAACTCGTTACTCGTTCTCCACGACTACTCGTTTACTCGTTACTCGTTTGATAGGACTCGTTACTCGTTTTACTCGTTCCTACTCGTTCTACTCGTTACTCGTTCTACTCGTTTTTTACTCGTTACTCGTTACTCGTTACTCGTTGACCACTCGTTGGAACTCGTTGTTCATCACTCGTTCAATGTACTCGTTTGACTCGTTTTGGTACATGAACTCGTTGTGAACTCGTTACTCGTTACTCGTTTAGCACTCGTTGCCACTCGTTACTCGTTCGACTCGTTTTAACTCGTTTACTCGTTGTATTACAACTCGTTTACTCGTTACTCGTTCTACTCGTTACTCGTTAACTCGTTACTCGTTAACACACTCGTTCAGACTCGTTCGCCCCCGAAACTCGTTACTCGTTGTCACTCGTTACTCGTTACTCGTTCTGGACTCGTTCACTCGTTGACTCGTTTCCAACTCGTTAACTCGTTTTTTAATACTCGTTGGCACTCGTTTGACTCGTTACTCGTTAATGACTCGTTACTCGTTACTCGTTTCTCATCGAACTCGTTGACTCGTTCACTCGTTCAACTCGTTACTCGTTATGGACTCGTTACAAGCTACTCGTTCTAACTCGTTACTCGTTATTGATATCTTTAACAACTCGTTCCGTAGACTCGTTACTCGTTACTCGTTAACTCGTTACTCGTTAGACTCGTTAACTCACTCGTTACTCGTT";
$pattern = "ACTCGTTAC";
$count = patternCount($text, $pattern);
echo "Text = $text <br/>";
echo "Pattern = $pattern <br/>";
echo "Count = $count <br/>";
function patternCount($text, $pattern) {
    $count = 0;
    for ($i = 0; $i <= strlen($text) - strlen($pattern); $i++ ) {
        if(substr($text, $i, strlen($pattern)) == $pattern) {
            $count++;
        }
    } 
    return $count;
}
?>